name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: treksterdb
        ports:
          - 5431:5431
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    - name: Install EF Core CLI
      run: |
        dotnet tool install --global dotnet-ef --version 7.*
        echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

    - name: Restore dependencies
      run: dotnet restore Trekster_web/Trekster_web.sln

    - name: Build solution
      run: dotnet build Trekster_web/Trekster_web.sln --no-restore

    - name: Run EF Migrations
      env:
        ConnectionStrings__DefaultConnection: "Host=localhost;Port=5431;Database=treksterdb;Username=postgres;Password=1234;"
      run: |
        dotnet ef database update \
          --project Trekster_web/Trekster_web/Trekster_web.csproj \
          --startup-project Trekster_web/Trekster_web/Trekster_web.csproj
    # ────────────────────────────────────────────────────────────────────────────

    - name: Run unit/integration tests (excluding UI)
      run: dotnet test Trekster_web/Trekster_web.sln --no-build --verbosity normal --filter "FullyQualifiedName!~TreksterUISeleniumTests"

    - name: Publish Trekster for CI
      run: dotnet publish Trekster_web/Trekster_web/Trekster_web.csproj -c Release -o publish

    - name: Serve Trekster
      env:
        ASPNETCORE_URLS:        "http://0.0.0.0:7034"
        ASPNETCORE_ENVIRONMENT: Development
        TESTUSER__EMAIL:        ${{ secrets.Email }}
        TESTUSER__PASSWORD:     ${{ secrets.Password }}
        ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=treksterdb;Username=postgres;Password=1234;"
      run: |
        cd publish
        nohup dotnet Trekster_web.dll > ../trekster.log 2>&1 &
        cd ..
        sleep 10
        lsof -iTCP:7034 -sTCP:LISTEN || (cat trekster.log && exit 1)
        curl -v http://localhost:7034
    
    - name: Health check
      run: |
        curl -v http://127.0.0.1:7034 || curl -v http://localhost:7034
    
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    
    - name: Restore & run Selenium UI Tests
      env:
        EMAIL:    ${{ secrets.Email }}
        PASSWORD: ${{ secrets.Password }}
        ConnectionStrings__DefaultConnection: "Host=localhost;Port=5431;Database=treksterdb;Username=postgres;Password=1234;"
      run: |
        dotnet restore Testing/TreksterUISeleniumTests/TreksterUISeleniumTests/TreksterUISeleniumTests.csproj
        dotnet test Testing/TreksterUISeleniumTests/TreksterUISeleniumTests/TreksterUISeleniumTests.csproj --verbosity normal
