name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore Trekster_web/Trekster_web.sln

    - name: Build solution
      run: dotnet build Trekster_web/Trekster_web.sln --no-restore

    - name: Run unit/integration tests (excluding UI)
      run: dotnet test Trekster_web/Trekster_web.sln --no-build --verbosity normal --filter "FullyQualifiedName!~TreksterUISeleniumTests"

    - name: Publish Trekster for CI
      run: dotnet publish Trekster_web/Trekster_web/Trekster_web.csproj -c Release -o publish

    - name: Serve Trekster on port 7034
      env:
        ASPNETCORE_URLS: "http://0.0.0.0:7034"
      run: |
        # start the app in background, capture logs
        nohup dotnet publish/Trekster_web.dll > trekster.log 2>&1 &
        # give it a bit longer to spin up
        sleep 10
        # sanity‑check that it's running
        lsof -iTCP:7034 -sTCP:LISTEN || (echo ">> no listener on 7034 <<" && cat trekster.log && exit 1)
    
    - name: Health check
      run: |
        # sometimes localhost resolves IPv6; test both
        curl -v http://127.0.0.1:7034 || curl -v http://localhost:7034
    
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    
    - name: Restore & run Selenium UI Tests
      run: |
        dotnet restore Testing/TreksterUISeleniumTests/TreksterUISeleniumTests/TreksterUISeleniumTests.csproj
        dotnet test Testing/TreksterUISeleniumTests/TreksterUISeleniumTests/TreksterUISeleniumTests.csproj --verbosity normal
