# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore Trekster_web/Trekster_web.sln
    - name: Build
      run: dotnet build Trekster_web/Trekster_web.sln --no-restore
    - name: Test
      run: dotnet test Trekster_web/Trekster_web.sln --no-build --verbosity normal

    - name: Run Trekster app
      working-directory: Trekster_web/Trekster_web
      run: |
        dotnet run --urls "http://localhost:7034" &
        sleep 15

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Restore and run Selenium UI Tests
      working-directory: Testing/TreksterUISeleniumTests
      run: |
        dotnet restore
        dotnet test --no-build --verbosity normal
